//HintName: EmbeddedFiles.GetSecondFile.g.cs
// <auto-generated>
#nullable enable
using global::System.Runtime.CompilerServices;

namespace Hello
{
    internal static partial class EmbeddedFiles
    {
        [CompilerGenerated]
        private static byte[] _GetSecondFile = new byte[]{0x54, 0x68, 0x69, 0x73, 0x20, 0x69, 0x73, 0x20, 0x74, 0x68, 0x65, 0x20, 0x73, 0x65, 0x63, 0x6F, 0x6E, 0x64, 0x20, 0x66, 0x69, 0x6C, 0x65};
        [CompilerGenerated]
        private static partial byte[] GetSecondFile()
        {
            return _GetSecondFile;
        }
    }
}