using Microsoft.CodeAnalysis;

namespace Arcasharp.Embed.SourceGenerator;

internal static class EmbedFileAttributeSourceGeneratorOutput
{
    public const string AttributeName = "EmbedFileAttribute";
    public const string NameArgument = "Name";
    private const string Namespace = "Arcasharp.Embed";
    private const string HintFileName = $"{AttributeName}.g.cs";

    public static void AddAttribute(IncrementalGeneratorPostInitializationContext context)
    {
        string source = $$"""
                          // <auto-generated>
                          #nullable enable

                          using global::System;
                          using global::System.Runtime.CompilerServices;

                          namespace {{Namespace}} {
                              
                              /// <summary>
                              /// Embeds a file into the assembly
                              /// </summary>
                              [AttributeUsage(AttributeTargets.Method)]
                              [CompilerGenerated]
                              public sealed class {{AttributeName}} : Attribute
                              {
                                  /// <summary>
                                  /// Create an instance of {{AttributeName}}
                                  /// </summary>
                                  /// <param name="Name">The absolute or relative path to the file to embed (relative to the project root path)</param>
                                  public {{AttributeName}}(string {{NameArgument}})
                                  {
                                  
                                  }
                              }
                          }
                          """;

        context.AddSource(HintFileName, source);
    }
}